### PR TITLE
Upgrade to v2.3.1

### PR DESCRIPTION
**Pull request by jleni**

### CODE REVIEW

**Comment by pscott** [comment]
Can yo usolve the conflicts please? :D

**Comment by tjanez** [comment]
> Could you solve the conflicts please? :D Then I'll merge & deploy on our testnet :)

@pscott, the conflicts have been resolved. Thanks, @ftheirs!

**Comment by valentinbud** [comment]
Hello @pscott. Have you managed to deploy the changes in your testnet so far?
We're quite a lot of members in the Oasis Community that use Ledger and this
update would benefit us all. Thanks!

**Comment by billxljin** [comment]
Hello @pscott. Have you managed to deploy the changes in your testnet so far? waiting for this PR to continue my task, thank you!

**Pull request merged**
